#!/usr/bin/env python3
"""Simple script that prints 'hello'."""

def main():
	print("hello")


if __name__ == "__main__":
	main()
"""Simple script that prints 'hello'."""

def main():
	print("hello")


if __name__ == "__main__":
	main()


